# docker-compose.yml
version: "3.8"
services:
  db:
    image: postgres:15
    container_name: mintique-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mintique
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
